name: earthquake-detection
channels:
  - conda-forge
  - defaults
dependencies:
  - boto3=1.34.69
  - fsspec=2024.6.1
  - ipykernel=6.29.5
  - jupyterlab=4.2.5
  - python=3.12.3
  - numpy=2.0.1
  - pandas=2.2.3
  - matplotlib=3.9.2
  - s3fs=2024.6.1
  - scikit-learn=1.5.2
  - pip=24.2
  - pip:
    - requests=2.32.3