name: earthquake-detection
channels:
  - conda-forge
  - defaults
dependencies:
  - boto3=1.34.69
  - cartopy=0.22.0
  - fastapi=0.112.2
  - fsspec=2024.6.1
  - httpx=0.28.1
  - ipykernel=6.29.5
  - jupyterlab=4.2.5
  - matplotlib=3.9.2
  - numpy=1.26.4
  - pandas=2.2.3
  - pillow=11.0.0
  - pip=24.2
  - plac=1.3.4
  - pydantic=2.10.3
  - python=3.12.3
  - requests==2.32.3
  - s3fs=2024.6.1
  - scikit-learn=1.5.2
  - tensorflow=2.17.0
  - tqdm=4.66.5
  - uvicorn=0.32.1
  - pip:
    - h5py==3.12.1
    - obspy==1.4.1
    - pyasynchat==1.0.4
    - pyasyncore==1.0.4